codecov:
    token: e74ecbf3-de62-42fc-bc20-ad473cd0d7a9
    notify:
      require_ci_to_pass: yes
  
  coverage:
    precision: 2
    round: down
    range: 50...100
  
    status:
      # Learn more at https://codecov.io/docs#yaml_default_commit_status
      project: true
      patch: true
      changes: false
  
    # We don't want statistics for the tests themselves and certainly not for the
    # benchmarks and boost libraries. Note that while we exclude the gcov data for
    # these patterns in the codecov call (codecov --gcov-glob ...), the fact that
    # our code references these areas also means we need to tell codecov itself to
    # ignore them from the stats.
    ignore:
    - 'Build'
    - 'Lib'
    - 'Test'
  
  comment:
    layout: "header, diff, changes, uncovered"
    behavior: default  # update if exists else create new