name: LinuxBuild
on: [push]

jobs:
    install_build_dependency:
        name: install cmake
        runs-on: ubuntu-latest
        steps:
            - name: install latest cmake
              uses: lukka/get-cmake@latest
            - name: install build essential
              run: sudo apt-get install build-essential
        
    debug_build:
        name: debug build
        runs-on: ubuntu-latest
        needs: [install_build_dependency]
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: make cmake-build directory
              run: mkdir cmake-build
              shell: bash
            - name: install lcov
              run: sudo apt-get install lcov
            - name: debug configure
              run: cmake .. -DCMAKE_BUILD_TYPE=Debug
              shell: bash
              working-directory: ./cmake-build
            - name: debug build
              run: cmake --build . --config Debug
              shell: bash
              working-directory: ./cmake-build
            - name: run ctest and make coverage coverage
              run: make coverage
              shell: bash
              working-directory: ./cmake-build
            - name: upload coverage info to codecov
              uses: codecov/codecov-action@v1

    release_build:
        name: release build
        runs-on: ubuntu-latest
        needs: [install_build_dependency]
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: make cmake-build directory
              run: mkdir cmake-build
              shell: bash
            - name: release configure
              run: cmake .. -DCMAKE_BUILD_TYPE=Release
              shell: bash
              working-directory: ./cmake-build
            - name: release build
              run: cmake --build . --config Release
              shell: bash
              working-directory: ./cmake-build
            - name: run test -C Release
              run: ctest -C Release
              shell: bash
              working-directory: ./cmake-build